// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.5.1
// source: rufs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Certificate []byte `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type ConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoints []string `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*ConnectResponse_PeerList_
	//	*ConnectResponse_ActiveDownloads
	//	*ConnectResponse_ResolveConflictRequest
	Msg isConnectResponse_Msg `protobuf_oneof:"msg"`
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{3}
}

func (m *ConnectResponse) GetMsg() isConnectResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ConnectResponse) GetPeerList() *ConnectResponse_PeerList {
	if x, ok := x.GetMsg().(*ConnectResponse_PeerList_); ok {
		return x.PeerList
	}
	return nil
}

func (x *ConnectResponse) GetActiveDownloads() *ConnectResponse_ActiveDownloadList {
	if x, ok := x.GetMsg().(*ConnectResponse_ActiveDownloads); ok {
		return x.ActiveDownloads
	}
	return nil
}

func (x *ConnectResponse) GetResolveConflictRequest() *ResolveConflictRequest {
	if x, ok := x.GetMsg().(*ConnectResponse_ResolveConflictRequest); ok {
		return x.ResolveConflictRequest
	}
	return nil
}

type isConnectResponse_Msg interface {
	isConnectResponse_Msg()
}

type ConnectResponse_PeerList_ struct {
	PeerList *ConnectResponse_PeerList `protobuf:"bytes,1,opt,name=peer_list,json=peerList,proto3,oneof"`
}

type ConnectResponse_ActiveDownloads struct {
	ActiveDownloads *ConnectResponse_ActiveDownloadList `protobuf:"bytes,2,opt,name=active_downloads,json=activeDownloads,proto3,oneof"`
}

type ConnectResponse_ResolveConflictRequest struct {
	ResolveConflictRequest *ResolveConflictRequest `protobuf:"bytes,3,opt,name=resolve_conflict_request,json=resolveConflictRequest,proto3,oneof"`
}

func (*ConnectResponse_PeerList_) isConnectResponse_Msg() {}

func (*ConnectResponse_ActiveDownloads) isConnectResponse_Msg() {}

func (*ConnectResponse_ResolveConflictRequest) isConnectResponse_Msg() {}

type GetMyIPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMyIPRequest) Reset() {
	*x = GetMyIPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyIPRequest) ProtoMessage() {}

func (x *GetMyIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyIPRequest.ProtoReflect.Descriptor instead.
func (*GetMyIPRequest) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{4}
}

type GetMyIPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *GetMyIPResponse) Reset() {
	*x = GetMyIPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyIPResponse) ProtoMessage() {}

func (x *GetMyIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyIPResponse.ProtoReflect.Descriptor instead.
func (*GetMyIPResponse) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{5}
}

func (x *GetMyIPResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Peer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoints []string `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
}

func (x *Peer) Reset() {
	*x = Peer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{6}
}

func (x *Peer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Peer) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type ResolveConflictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *ResolveConflictRequest) Reset() {
	*x = ResolveConflictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveConflictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveConflictRequest) ProtoMessage() {}

func (x *ResolveConflictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveConflictRequest.ProtoReflect.Descriptor instead.
func (*ResolveConflictRequest) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveConflictRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ResolveConflictResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResolveConflictResponse) Reset() {
	*x = ResolveConflictResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveConflictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveConflictResponse) ProtoMessage() {}

func (x *ResolveConflictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveConflictResponse.ProtoReflect.Descriptor instead.
func (*ResolveConflictResponse) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{8}
}

type OrchestrateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*OrchestrateRequest_StartOrchestration
	//	*OrchestrateRequest_UpdateByteRanges_
	//	*OrchestrateRequest_ConnectedPeers_
	//	*OrchestrateRequest_UploadFailed_
	Msg isOrchestrateRequest_Msg `protobuf_oneof:"msg"`
}

func (x *OrchestrateRequest) Reset() {
	*x = OrchestrateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateRequest) ProtoMessage() {}

func (x *OrchestrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateRequest.ProtoReflect.Descriptor instead.
func (*OrchestrateRequest) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{9}
}

func (m *OrchestrateRequest) GetMsg() isOrchestrateRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *OrchestrateRequest) GetStartOrchestration() *OrchestrateRequest_StartOrchestrationRequest {
	if x, ok := x.GetMsg().(*OrchestrateRequest_StartOrchestration); ok {
		return x.StartOrchestration
	}
	return nil
}

func (x *OrchestrateRequest) GetUpdateByteRanges() *OrchestrateRequest_UpdateByteRanges {
	if x, ok := x.GetMsg().(*OrchestrateRequest_UpdateByteRanges_); ok {
		return x.UpdateByteRanges
	}
	return nil
}

func (x *OrchestrateRequest) GetConnectedPeers() *OrchestrateRequest_ConnectedPeers {
	if x, ok := x.GetMsg().(*OrchestrateRequest_ConnectedPeers_); ok {
		return x.ConnectedPeers
	}
	return nil
}

func (x *OrchestrateRequest) GetUploadFailed() *OrchestrateRequest_UploadFailed {
	if x, ok := x.GetMsg().(*OrchestrateRequest_UploadFailed_); ok {
		return x.UploadFailed
	}
	return nil
}

type isOrchestrateRequest_Msg interface {
	isOrchestrateRequest_Msg()
}

type OrchestrateRequest_StartOrchestration struct {
	StartOrchestration *OrchestrateRequest_StartOrchestrationRequest `protobuf:"bytes,1,opt,name=start_orchestration,json=startOrchestration,proto3,oneof"`
}

type OrchestrateRequest_UpdateByteRanges_ struct {
	UpdateByteRanges *OrchestrateRequest_UpdateByteRanges `protobuf:"bytes,2,opt,name=update_byte_ranges,json=updateByteRanges,proto3,oneof"`
}

type OrchestrateRequest_ConnectedPeers_ struct {
	ConnectedPeers *OrchestrateRequest_ConnectedPeers `protobuf:"bytes,3,opt,name=connected_peers,json=connectedPeers,proto3,oneof"`
}

type OrchestrateRequest_UploadFailed_ struct {
	UploadFailed *OrchestrateRequest_UploadFailed `protobuf:"bytes,4,opt,name=upload_failed,json=uploadFailed,proto3,oneof"`
}

func (*OrchestrateRequest_StartOrchestration) isOrchestrateRequest_Msg() {}

func (*OrchestrateRequest_UpdateByteRanges_) isOrchestrateRequest_Msg() {}

func (*OrchestrateRequest_ConnectedPeers_) isOrchestrateRequest_Msg() {}

func (*OrchestrateRequest_UploadFailed_) isOrchestrateRequest_Msg() {}

type OrchestrateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*OrchestrateResponse_Welcome_
	//	*OrchestrateResponse_PeerList_
	//	*OrchestrateResponse_UploadCommand_
	Msg isOrchestrateResponse_Msg `protobuf_oneof:"msg"`
}

func (x *OrchestrateResponse) Reset() {
	*x = OrchestrateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateResponse) ProtoMessage() {}

func (x *OrchestrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateResponse.ProtoReflect.Descriptor instead.
func (*OrchestrateResponse) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{10}
}

func (m *OrchestrateResponse) GetMsg() isOrchestrateResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *OrchestrateResponse) GetWelcome() *OrchestrateResponse_Welcome {
	if x, ok := x.GetMsg().(*OrchestrateResponse_Welcome_); ok {
		return x.Welcome
	}
	return nil
}

func (x *OrchestrateResponse) GetPeerList() *OrchestrateResponse_PeerList {
	if x, ok := x.GetMsg().(*OrchestrateResponse_PeerList_); ok {
		return x.PeerList
	}
	return nil
}

func (x *OrchestrateResponse) GetUploadCommand() *OrchestrateResponse_UploadCommand {
	if x, ok := x.GetMsg().(*OrchestrateResponse_UploadCommand_); ok {
		return x.UploadCommand
	}
	return nil
}

type isOrchestrateResponse_Msg interface {
	isOrchestrateResponse_Msg()
}

type OrchestrateResponse_Welcome_ struct {
	Welcome *OrchestrateResponse_Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type OrchestrateResponse_PeerList_ struct {
	PeerList *OrchestrateResponse_PeerList `protobuf:"bytes,2,opt,name=peer_list,json=peerList,proto3,oneof"`
}

type OrchestrateResponse_UploadCommand_ struct {
	UploadCommand *OrchestrateResponse_UploadCommand `protobuf:"bytes,3,opt,name=upload_command,json=uploadCommand,proto3,oneof"`
}

func (*OrchestrateResponse_Welcome_) isOrchestrateResponse_Msg() {}

func (*OrchestrateResponse_PeerList_) isOrchestrateResponse_Msg() {}

func (*OrchestrateResponse_UploadCommand_) isOrchestrateResponse_Msg() {}

type Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End   int64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *Range) Reset() {
	*x = Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{11}
}

func (x *Range) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Range) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type ReadDirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ReadDirRequest) Reset() {
	*x = ReadDirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirRequest) ProtoMessage() {}

func (x *ReadDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirRequest.ProtoReflect.Descriptor instead.
func (*ReadDirRequest) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{12}
}

func (x *ReadDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadDirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*File `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *ReadDirResponse) Reset() {
	*x = ReadDirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirResponse) ProtoMessage() {}

func (x *ReadDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirResponse.ProtoReflect.Descriptor instead.
func (*ReadDirResponse) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{13}
}

func (x *ReadDirResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// Optional
	Hash        string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	IsDirectory bool   `protobuf:"varint,3,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	Size        int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Mtime       int64  `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"` // UNIX timestamp
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{14}
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *File) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *File) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

type ReadFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Offset   int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Rdnow    int64  `protobuf:"varint,3,opt,name=rdnow,proto3" json:"rdnow,omitempty"`
	Rdahead  int64  `protobuf:"varint,4,opt,name=rdahead,proto3" json:"rdahead,omitempty"`
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{15}
}

func (x *ReadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReadFileRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileRequest) GetRdnow() int64 {
	if x != nil {
		return x.Rdnow
	}
	return 0
}

func (x *ReadFileRequest) GetRdahead() int64 {
	if x != nil {
		return x.Rdahead
	}
	return 0
}

type ReadFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset                         int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data                           []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	RedirectToOrchestratedDownload int64  `protobuf:"varint,6,opt,name=redirect_to_orchestrated_download,json=redirectToOrchestratedDownload,proto3" json:"redirect_to_orchestrated_download,omitempty"`
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{16}
}

func (x *ReadFileResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadFileResponse) GetRedirectToOrchestratedDownload() int64 {
	if x != nil {
		return x.RedirectToOrchestratedDownload
	}
	return 0
}

type PassiveTransferData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownloadId int64  `protobuf:"varint,1,opt,name=download_id,json=downloadId,proto3" json:"download_id,omitempty"`
	Offset     int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data       []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PassiveTransferData) Reset() {
	*x = PassiveTransferData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassiveTransferData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassiveTransferData) ProtoMessage() {}

func (x *PassiveTransferData) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassiveTransferData.ProtoReflect.Descriptor instead.
func (*PassiveTransferData) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{17}
}

func (x *PassiveTransferData) GetDownloadId() int64 {
	if x != nil {
		return x.DownloadId
	}
	return 0
}

func (x *PassiveTransferData) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PassiveTransferData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConnectResponse_PeerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peers []*Peer `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *ConnectResponse_PeerList) Reset() {
	*x = ConnectResponse_PeerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse_PeerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse_PeerList) ProtoMessage() {}

func (x *ConnectResponse_PeerList) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse_PeerList.ProtoReflect.Descriptor instead.
func (*ConnectResponse_PeerList) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ConnectResponse_PeerList) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type ConnectResponse_ActiveDownload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownloadId int64    `protobuf:"varint,1,opt,name=download_id,json=downloadId,proto3" json:"download_id,omitempty"`
	Hash       string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Filenames  []string `protobuf:"bytes,3,rep,name=filenames,proto3" json:"filenames,omitempty"`
}

func (x *ConnectResponse_ActiveDownload) Reset() {
	*x = ConnectResponse_ActiveDownload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse_ActiveDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse_ActiveDownload) ProtoMessage() {}

func (x *ConnectResponse_ActiveDownload) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse_ActiveDownload.ProtoReflect.Descriptor instead.
func (*ConnectResponse_ActiveDownload) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ConnectResponse_ActiveDownload) GetDownloadId() int64 {
	if x != nil {
		return x.DownloadId
	}
	return 0
}

func (x *ConnectResponse_ActiveDownload) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ConnectResponse_ActiveDownload) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

type ConnectResponse_ActiveDownloadList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveDownloads []*ConnectResponse_ActiveDownload `protobuf:"bytes,1,rep,name=active_downloads,json=activeDownloads,proto3" json:"active_downloads,omitempty"`
}

func (x *ConnectResponse_ActiveDownloadList) Reset() {
	*x = ConnectResponse_ActiveDownloadList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse_ActiveDownloadList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse_ActiveDownloadList) ProtoMessage() {}

func (x *ConnectResponse_ActiveDownloadList) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse_ActiveDownloadList.ProtoReflect.Descriptor instead.
func (*ConnectResponse_ActiveDownloadList) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{3, 2}
}

func (x *ConnectResponse_ActiveDownloadList) GetActiveDownloads() []*ConnectResponse_ActiveDownload {
	if x != nil {
		return x.ActiveDownloads
	}
	return nil
}

type OrchestrateRequest_StartOrchestrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownloadId int64  `protobuf:"varint,1,opt,name=download_id,json=downloadId,proto3" json:"download_id,omitempty"`
	Filename   string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Hash       string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *OrchestrateRequest_StartOrchestrationRequest) Reset() {
	*x = OrchestrateRequest_StartOrchestrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestrateRequest_StartOrchestrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateRequest_StartOrchestrationRequest) ProtoMessage() {}

func (x *OrchestrateRequest_StartOrchestrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateRequest_StartOrchestrationRequest.ProtoReflect.Descriptor instead.
func (*OrchestrateRequest_StartOrchestrationRequest) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{9, 0}
}

func (x *OrchestrateRequest_StartOrchestrationRequest) GetDownloadId() int64 {
	if x != nil {
		return x.DownloadId
	}
	return 0
}

func (x *OrchestrateRequest_StartOrchestrationRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *OrchestrateRequest_StartOrchestrationRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type OrchestrateRequest_UpdateByteRanges struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Have      []*Range `protobuf:"bytes,1,rep,name=have,proto3" json:"have,omitempty"`
	Readnow   []*Range `protobuf:"bytes,2,rep,name=readnow,proto3" json:"readnow,omitempty"`
	Readahead []*Range `protobuf:"bytes,3,rep,name=readahead,proto3" json:"readahead,omitempty"`
}

func (x *OrchestrateRequest_UpdateByteRanges) Reset() {
	*x = OrchestrateRequest_UpdateByteRanges{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestrateRequest_UpdateByteRanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateRequest_UpdateByteRanges) ProtoMessage() {}

func (x *OrchestrateRequest_UpdateByteRanges) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateRequest_UpdateByteRanges.ProtoReflect.Descriptor instead.
func (*OrchestrateRequest_UpdateByteRanges) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{9, 1}
}

func (x *OrchestrateRequest_UpdateByteRanges) GetHave() []*Range {
	if x != nil {
		return x.Have
	}
	return nil
}

func (x *OrchestrateRequest_UpdateByteRanges) GetReadnow() []*Range {
	if x != nil {
		return x.Readnow
	}
	return nil
}

func (x *OrchestrateRequest_UpdateByteRanges) GetReadahead() []*Range {
	if x != nil {
		return x.Readahead
	}
	return nil
}

type OrchestrateRequest_ConnectedPeers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peers []string `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *OrchestrateRequest_ConnectedPeers) Reset() {
	*x = OrchestrateRequest_ConnectedPeers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestrateRequest_ConnectedPeers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateRequest_ConnectedPeers) ProtoMessage() {}

func (x *OrchestrateRequest_ConnectedPeers) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateRequest_ConnectedPeers.ProtoReflect.Descriptor instead.
func (*OrchestrateRequest_ConnectedPeers) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{9, 2}
}

func (x *OrchestrateRequest_ConnectedPeers) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

type OrchestrateRequest_UploadFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetPeers []string `protobuf:"bytes,1,rep,name=target_peers,json=targetPeers,proto3" json:"target_peers,omitempty"`
}

func (x *OrchestrateRequest_UploadFailed) Reset() {
	*x = OrchestrateRequest_UploadFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestrateRequest_UploadFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateRequest_UploadFailed) ProtoMessage() {}

func (x *OrchestrateRequest_UploadFailed) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateRequest_UploadFailed.ProtoReflect.Descriptor instead.
func (*OrchestrateRequest_UploadFailed) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{9, 3}
}

func (x *OrchestrateRequest_UploadFailed) GetTargetPeers() []string {
	if x != nil {
		return x.TargetPeers
	}
	return nil
}

type OrchestrateResponse_Welcome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownloadId int64 `protobuf:"varint,1,opt,name=download_id,json=downloadId,proto3" json:"download_id,omitempty"`
}

func (x *OrchestrateResponse_Welcome) Reset() {
	*x = OrchestrateResponse_Welcome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestrateResponse_Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateResponse_Welcome) ProtoMessage() {}

func (x *OrchestrateResponse_Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateResponse_Welcome.ProtoReflect.Descriptor instead.
func (*OrchestrateResponse_Welcome) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{10, 0}
}

func (x *OrchestrateResponse_Welcome) GetDownloadId() int64 {
	if x != nil {
		return x.DownloadId
	}
	return 0
}

type OrchestrateResponse_PeerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peers []string `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *OrchestrateResponse_PeerList) Reset() {
	*x = OrchestrateResponse_PeerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestrateResponse_PeerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateResponse_PeerList) ProtoMessage() {}

func (x *OrchestrateResponse_PeerList) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateResponse_PeerList.ProtoReflect.Descriptor instead.
func (*OrchestrateResponse_PeerList) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{10, 1}
}

func (x *OrchestrateResponse_PeerList) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

type OrchestrateResponse_UploadCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer  string `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Range *Range `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
}

func (x *OrchestrateResponse_UploadCommand) Reset() {
	*x = OrchestrateResponse_UploadCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rufs_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestrateResponse_UploadCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateResponse_UploadCommand) ProtoMessage() {}

func (x *OrchestrateResponse_UploadCommand) ProtoReflect() protoreflect.Message {
	mi := &file_rufs_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateResponse_UploadCommand.ProtoReflect.Descriptor instead.
func (*OrchestrateResponse_UploadCommand) Descriptor() ([]byte, []int) {
	return file_rufs_proto_rawDescGZIP(), []int{10, 2}
}

func (x *OrchestrateResponse_UploadCommand) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *OrchestrateResponse_UploadCommand) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

var File_rufs_proto protoreflect.FileDescriptor

var file_rufs_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x75, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x0f,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x22, 0x34, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x2e, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0xe9, 0x03, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x50, 0x65, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x10, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x53, 0x0a, 0x18, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x16, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x6c, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x0a, 0x08, 0x50,
	0x65, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x05, 0x70,
	0x65, 0x65, 0x72, 0x73, 0x1a, 0x63, 0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x1a, 0x60, 0x0a, 0x12, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x4a, 0x0a, 0x10, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x0f, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x49, 0x50, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x49, 0x50, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x38, 0x0a, 0x04, 0x50, 0x65, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x22, 0x34, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x6c, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0xac, 0x05, 0x0a, 0x12, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x60, 0x0a, 0x13, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x12, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x72,
	0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x54, 0x0a, 0x12, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x42, 0x79, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x48, 0x00, 0x52,
	0x10, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x73, 0x12, 0x4d, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x70,
	0x65, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x4f, 0x72, 0x63,
	0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x50, 0x65, 0x65, 0x72, 0x73, 0x48, 0x00,
	0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x50, 0x65, 0x65, 0x72, 0x73,
	0x12, 0x47, 0x0a, 0x0d, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x1a, 0x6c, 0x0a, 0x19, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x1a, 0x76, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x79, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x04, 0x68,
	0x61, 0x76, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x04, 0x68, 0x61, 0x76, 0x65, 0x12, 0x20, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x6e,
	0x6f, 0x77, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x6e, 0x6f, 0x77, 0x12, 0x24, 0x0a, 0x09, 0x72, 0x65, 0x61,
	0x64, 0x61, 0x68, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x09, 0x72, 0x65, 0x61, 0x64, 0x61, 0x68, 0x65, 0x61, 0x64, 0x1a,
	0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x50, 0x65, 0x65, 0x72,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x1a, 0x31, 0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0xf2, 0x02, 0x0a, 0x13, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x77, 0x65, 0x6c,
	0x63, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x4f, 0x72, 0x63,
	0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x07, 0x77, 0x65, 0x6c, 0x63,
	0x6f, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x65, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x4b, 0x0a, 0x0e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x4f, 0x72, 0x63, 0x68,
	0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52,
	0x0d, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x2a,
	0x0a, 0x07, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x1a, 0x20, 0x0a, 0x08, 0x50, 0x65,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x1a, 0x41, 0x0a, 0x0d,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x65, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x06, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x42,
	0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2f, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x44,
	0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x2e, 0x0a,
	0x0f, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x83, 0x01,
	0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x75, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x64,
	0x6e, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x64, 0x6e, 0x6f, 0x77,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x64, 0x61, 0x68, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x72, 0x64, 0x61, 0x68, 0x65, 0x61, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x10, 0x52,
	0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x49, 0x0a, 0x21, 0x72,
	0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x6f, 0x5f, 0x6f, 0x72, 0x63, 0x68, 0x65,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1e, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x54, 0x6f, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x64, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x62, 0x0a, 0x13, 0x50, 0x61, 0x73, 0x73, 0x69, 0x76,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a,
	0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xaf, 0x02, 0x0a, 0x10, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x31, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x30, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x0f, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x2e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x49, 0x50, 0x12,
	0x0f, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x49, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x12, 0x17, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x6c, 0x69,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b,
	0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x4f, 0x72,
	0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x32, 0xba, 0x01, 0x0a,
	0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x2e, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x12, 0x0f, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x33, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x43, 0x0a, 0x0f, 0x50, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x69, 0x76,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x14, 0x2e,
	0x50, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x67, 0x69, 0x65, 0x6c, 0x65, 0x6e, 0x2f,
	0x72, 0x75, 0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rufs_proto_rawDescOnce sync.Once
	file_rufs_proto_rawDescData = file_rufs_proto_rawDesc
)

func file_rufs_proto_rawDescGZIP() []byte {
	file_rufs_proto_rawDescOnce.Do(func() {
		file_rufs_proto_rawDescData = protoimpl.X.CompressGZIP(file_rufs_proto_rawDescData)
	})
	return file_rufs_proto_rawDescData
}

var file_rufs_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_rufs_proto_goTypes = []interface{}{
	(*RegisterRequest)(nil),                              // 0: RegisterRequest
	(*RegisterResponse)(nil),                             // 1: RegisterResponse
	(*ConnectRequest)(nil),                               // 2: ConnectRequest
	(*ConnectResponse)(nil),                              // 3: ConnectResponse
	(*GetMyIPRequest)(nil),                               // 4: GetMyIPRequest
	(*GetMyIPResponse)(nil),                              // 5: GetMyIPResponse
	(*Peer)(nil),                                         // 6: Peer
	(*ResolveConflictRequest)(nil),                       // 7: ResolveConflictRequest
	(*ResolveConflictResponse)(nil),                      // 8: ResolveConflictResponse
	(*OrchestrateRequest)(nil),                           // 9: OrchestrateRequest
	(*OrchestrateResponse)(nil),                          // 10: OrchestrateResponse
	(*Range)(nil),                                        // 11: Range
	(*ReadDirRequest)(nil),                               // 12: ReadDirRequest
	(*ReadDirResponse)(nil),                              // 13: ReadDirResponse
	(*File)(nil),                                         // 14: File
	(*ReadFileRequest)(nil),                              // 15: ReadFileRequest
	(*ReadFileResponse)(nil),                             // 16: ReadFileResponse
	(*PassiveTransferData)(nil),                          // 17: PassiveTransferData
	(*ConnectResponse_PeerList)(nil),                     // 18: ConnectResponse.PeerList
	(*ConnectResponse_ActiveDownload)(nil),               // 19: ConnectResponse.ActiveDownload
	(*ConnectResponse_ActiveDownloadList)(nil),           // 20: ConnectResponse.ActiveDownloadList
	(*OrchestrateRequest_StartOrchestrationRequest)(nil), // 21: OrchestrateRequest.StartOrchestrationRequest
	(*OrchestrateRequest_UpdateByteRanges)(nil),          // 22: OrchestrateRequest.UpdateByteRanges
	(*OrchestrateRequest_ConnectedPeers)(nil),            // 23: OrchestrateRequest.ConnectedPeers
	(*OrchestrateRequest_UploadFailed)(nil),              // 24: OrchestrateRequest.UploadFailed
	(*OrchestrateResponse_Welcome)(nil),                  // 25: OrchestrateResponse.Welcome
	(*OrchestrateResponse_PeerList)(nil),                 // 26: OrchestrateResponse.PeerList
	(*OrchestrateResponse_UploadCommand)(nil),            // 27: OrchestrateResponse.UploadCommand
}
var file_rufs_proto_depIdxs = []int32{
	18, // 0: ConnectResponse.peer_list:type_name -> ConnectResponse.PeerList
	20, // 1: ConnectResponse.active_downloads:type_name -> ConnectResponse.ActiveDownloadList
	7,  // 2: ConnectResponse.resolve_conflict_request:type_name -> ResolveConflictRequest
	21, // 3: OrchestrateRequest.start_orchestration:type_name -> OrchestrateRequest.StartOrchestrationRequest
	22, // 4: OrchestrateRequest.update_byte_ranges:type_name -> OrchestrateRequest.UpdateByteRanges
	23, // 5: OrchestrateRequest.connected_peers:type_name -> OrchestrateRequest.ConnectedPeers
	24, // 6: OrchestrateRequest.upload_failed:type_name -> OrchestrateRequest.UploadFailed
	25, // 7: OrchestrateResponse.welcome:type_name -> OrchestrateResponse.Welcome
	26, // 8: OrchestrateResponse.peer_list:type_name -> OrchestrateResponse.PeerList
	27, // 9: OrchestrateResponse.upload_command:type_name -> OrchestrateResponse.UploadCommand
	14, // 10: ReadDirResponse.files:type_name -> File
	6,  // 11: ConnectResponse.PeerList.peers:type_name -> Peer
	19, // 12: ConnectResponse.ActiveDownloadList.active_downloads:type_name -> ConnectResponse.ActiveDownload
	11, // 13: OrchestrateRequest.UpdateByteRanges.have:type_name -> Range
	11, // 14: OrchestrateRequest.UpdateByteRanges.readnow:type_name -> Range
	11, // 15: OrchestrateRequest.UpdateByteRanges.readahead:type_name -> Range
	11, // 16: OrchestrateResponse.UploadCommand.range:type_name -> Range
	0,  // 17: DiscoveryService.Register:input_type -> RegisterRequest
	2,  // 18: DiscoveryService.Connect:input_type -> ConnectRequest
	4,  // 19: DiscoveryService.GetMyIP:input_type -> GetMyIPRequest
	7,  // 20: DiscoveryService.ResolveConflict:input_type -> ResolveConflictRequest
	9,  // 21: DiscoveryService.Orchestrate:input_type -> OrchestrateRequest
	12, // 22: ContentService.ReadDir:input_type -> ReadDirRequest
	15, // 23: ContentService.ReadFile:input_type -> ReadFileRequest
	17, // 24: ContentService.PassiveTransfer:input_type -> PassiveTransferData
	1,  // 25: DiscoveryService.Register:output_type -> RegisterResponse
	3,  // 26: DiscoveryService.Connect:output_type -> ConnectResponse
	5,  // 27: DiscoveryService.GetMyIP:output_type -> GetMyIPResponse
	8,  // 28: DiscoveryService.ResolveConflict:output_type -> ResolveConflictResponse
	10, // 29: DiscoveryService.Orchestrate:output_type -> OrchestrateResponse
	13, // 30: ContentService.ReadDir:output_type -> ReadDirResponse
	16, // 31: ContentService.ReadFile:output_type -> ReadFileResponse
	17, // 32: ContentService.PassiveTransfer:output_type -> PassiveTransferData
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_rufs_proto_init() }
func file_rufs_proto_init() {
	if File_rufs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rufs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyIPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyIPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveConflictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveConflictResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestrateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestrateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PassiveTransferData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectResponse_PeerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectResponse_ActiveDownload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectResponse_ActiveDownloadList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestrateRequest_StartOrchestrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestrateRequest_UpdateByteRanges); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestrateRequest_ConnectedPeers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestrateRequest_UploadFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestrateResponse_Welcome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestrateResponse_PeerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rufs_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestrateResponse_UploadCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rufs_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ConnectResponse_PeerList_)(nil),
		(*ConnectResponse_ActiveDownloads)(nil),
		(*ConnectResponse_ResolveConflictRequest)(nil),
	}
	file_rufs_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*OrchestrateRequest_StartOrchestration)(nil),
		(*OrchestrateRequest_UpdateByteRanges_)(nil),
		(*OrchestrateRequest_ConnectedPeers_)(nil),
		(*OrchestrateRequest_UploadFailed_)(nil),
	}
	file_rufs_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*OrchestrateResponse_Welcome_)(nil),
		(*OrchestrateResponse_PeerList_)(nil),
		(*OrchestrateResponse_UploadCommand_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rufs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rufs_proto_goTypes,
		DependencyIndexes: file_rufs_proto_depIdxs,
		MessageInfos:      file_rufs_proto_msgTypes,
	}.Build()
	File_rufs_proto = out.File
	file_rufs_proto_rawDesc = nil
	file_rufs_proto_goTypes = nil
	file_rufs_proto_depIdxs = nil
}
