#!/bin/bash

LAUNCH_AGENT_SRC="/Applications/rufs.app/Contents/Resources/com.github.sgielen.rufs.plist"
LAUNCH_AGENT_DEST="$HOME/Library/LaunchAgents/com.github.sgielen.rufs.plist"

USER_UID="$(id -u $USER)"

/bin/launchctl asuser $USER_UID /bin/launchctl unload "$LAUNCH_AGENT_DEST"
rm -f "$LAUNCH_AGENT_DEST"

/bin/launchctl asuser $USER_UID /bin/cp "$LAUNCH_AGENT_SRC" "$LAUNCH_AGENT_DEST"
/bin/launchctl asuser $USER_UID /bin/launchctl load "$LAUNCH_AGENT_DEST"

exit 0
