name: Automatic release

on:
  push:
    tags:
      - 'v*.*'

jobs:

  prep_macos_pkg:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install macfuse
      run: brew install macfuse

    - name: Create macOS package
      run: bash publish/macos/make-release.sh

    - name: Upload darwin binary for release creation
      uses: actions/upload-artifact@v2
      with:
        name: macos_pkg
        path: publish/macos/rufs.pkg
        if-no-files-found: error
        retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: prep_macos_pkg
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Versioning
      run: go generate ./version/

    - name: Build for testing
      run: go build -tags withversion -o test/bin/ ./...

    - name: Test
      run: go test -v ./...

    - name: Create empty _publish directory
      run: mkdir _publish

    - name: Stage linux/amd64
      run: cp test/bin/client _publish/rufs-linux-amd64

    - name: Download macos pkg
      uses: actions/download-artifact@v2
      with:
        name: macos_pkg
        path: _publish/

    - name: Build for linux/arm64
      run: GOARCH=arm64 go build -tags withversion -o _publish/rufs-linux-arm64 ./client/

    - name: Install NSIS
      run: sudo apt-get install -y nsis nsis-pluginapi

    - name: Build for windows
      run: bash publish/windows/make-release.sh

    - name: Stage rufs-setup.exe
      run: cp publish/windows/rufs-setup.exe _publish/rufs-setup.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: _publish/*
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
