name: RUFS

on: [push, pull_request]

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build
      run: go generate ./version/ && go build -tags withversion -o test/bin/ ./...

    - name: Test
      run: go test -v ./...

  build_and_test_cgofuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
    - name: Install libfuse-dev
      run: sudo apt-get install libfuse-dev

    - name: Build
      run: go generate ./version/ && go build -tags withversion,cgofuse -o test/bin/ ./...

  build_for_windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build
      run: go generate ./version/ && GOOS=windows GOARCH=amd64 go build -tags withversion -ldflags -H=windowsgui -o rufs.exe ./client/
