name: RUFS

on: [push, pull_request]

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go generate version/ && go build -tags withversion -o test/bin/ ./...

    - name: Test
      run: go test -v ./...

  build_and_test_cgofuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install libfuse-dev
      run: apt install libfuse-dev

    - name: Build
      run: go generate version/ && go build -tags withversion,cgofuse -o test/bin/ ./...

    - name: Test
      run: go test -v ./...
